# Generated by Django 5.2.6 on 2025-10-01 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_delete_userfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TournamentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_1_score', models.IntegerField(blank=True, null=True)),
                ('day_2_score', models.IntegerField(blank=True, null=True)),
                ('day_3_score', models.IntegerField(blank=True, null=True)),
                ('day_4_score', models.IntegerField(blank=True, null=True)),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to='golf.golfer')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='golf.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'golfer')},
            },
        ),
    ]
