# Generated by Django 5.2.6 on 2025-10-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_tournament_tournamententry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='golfer',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
